export const en = {
    // Header
    headerSubtitle: "Bring your imagination to life. Describe, upload, and let our AI create stunning visuals for you.",

    // Prompt
    promptPlaceholder: "Describe the image you want to create (e.g., 'a futuristic cityscape at sunset')",

    // Image Uploader
    uploaderAlertUnsupported: "Unsupported file type. Please upload a PNG, JPG, GIF, or WebP.",
    uploaderAlertTooLarge: "File is too large. Max size is 10MB.",
    uploaderAlertProcessError: "Failed to process image.",
    uploaderCTA: "Click to upload or drag and drop",
    uploaderFormats: "PNG, JPG, GIF or WebP (MAX. 10MB)",
    uploaderRemoveImageLabel: "Remove image",

    // Generated Image Display
    generatedImagePlaceholderTitle: "Your generated image will appear here",
    generatedImagePlaceholderSubtitle: "Start by entering a prompt above",
    generating: "Generating Image...",
    download: "Download",
    generatedImageAlt: "Generated by AI",
    downloadFileName: "imaginai-image",

    // Action Buttons
    processing: "Processing...",
    generateImage: "Generate Image",
    editImage: "Edit Image",

    // App messages
    errorGenerate: "Failed to generate image. Please try again.",
    errorEdit: "Failed to edit image. Please try again.",
    generatedImageTitle: "Generated Image",
};
